#!/bin/sh


export DB_NAME=sea_battle_db
export DB_USER=egor
export DB_PASSWORD=root
export DB_HOST=localhost


# import pytest
#
# from diploma import settings


# @pytest.fixture(scope='session')
# def django_db_setup():
#     settings.DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.postgresql',
#         'HOST': 'localhost',
#         'NAME': 'sea_battle_db',
#     }
# DB_NAME="sea_battle_db"
# DB_USER="egor"
# DB_PASSWORD="root"
# DB_HOST="localhost"


# ytest /home/egor/PycharmProjects/TMS-diploma/sea_battle/api/tests/test_api_views.py::TestRegisterFormAPIViewSet
#
