# Generated by Django 2.1.3 on 2018-11-23 18:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_of_btlfld', models.PositiveSmallIntegerField(max_length=50)),
                ('map_of_btlfld', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battleship', jsonfield.fields.JSONField()),
                ('battlemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplay', to='sea_battle.BattleMap')),
            ],
        ),
    ]
