# Generated by Django 2.1.3 on 2019-01-07 22:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMap1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map1_of_btlfld', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('map2_of_btlfld', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='player1', max_length=30)),
                ('email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('opponent_user_name', models.CharField(default='player2', max_length=30)),
            ],
        ),
    ]
