# Generated by Django 2.1.7 on 2019-04-16 17:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoots', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, size=None, verbose_name='Shoots'), size=None)),
                ('fleet_old', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, null=True, size=None), default=list, size=None), default=list, size=None, verbose_name='Fleet_old')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, max_length=50, verbose_name='Name of the game')),
                ('size', models.PositiveSmallIntegerField(default=10)),
                ('date', models.DateField(verbose_name='Date of game')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Game_creator', to=settings.AUTH_USER_MODEL, verbose_name='Game creator')),
                ('joiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Game_joiner', to=settings.AUTH_USER_MODEL, verbose_name='Game joiner')),
                ('turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn', to=settings.AUTH_USER_MODEL, verbose_name='Turn of')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Winner')),
            ],
        ),
        migrations.AddField(
            model_name='battlemap',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_maps', to='sea_battle.Game', verbose_name='Game Id'),
        ),
        migrations.AddField(
            model_name='battlemap',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
    ]
