# Generated by Django 2.1.3 on 2019-01-10 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sea_battle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlemap',
            name='map2_of_bf',
        ),
        migrations.RemoveField(
            model_name='battlemap',
            name='opponent_user_name',
        ),
        migrations.AddField(
            model_name='battlemap',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
    ]
