# Generated by Django 2.1.3 on 2019-01-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BattleMap1',
            new_name='BattleMap',
        ),
    ]
