# Generated by Django 2.1.7 on 2019-04-16 17:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemap',
            name='fleet_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Fleet_new'),
        ),
    ]
