# Generated by Django 2.1.7 on 2019-04-16 16:38
import json

from django.db import migrations


def convert_data_to_json(apps, schema_editor):

    Battlemap = apps.get_model('sea_battle', 'battlemap')
    for obj in Battlemap.objects.all():
        obj.fleet_new = json.dumps(obj.fleet_old)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0002_battlemap_fleet_new'),
    ]

    operations = [
        migrations.RunPython(convert_data_to_json),
    ]
