# Generated by Django 2.1.3 on 2018-11-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0002_auto_20181123_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='player1', max_length=30)),
                ('email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('opponent_user_name', models.CharField(default='player2', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='battlemap',
            name='size_of_btlfld',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='battlemap',
            name='userfld',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_btlfld', to='sea_battle.UserData'),
        ),
    ]
