# Generated by Django 2.1.7 on 2019-03-29 19:59

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0002_auto_20190316_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemap',
            name='shoots',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=200),
        ),
    ]
