# Generated by Django 2.1.7 on 2019-04-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0004_auto_20190417_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlemap',
            old_name='fleet_new',
            new_name='fleet',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='battlemap',
            name='fleet_old',
        ),
        migrations.AddField(
            model_name='battlemap',
            name='template',
            field=models.BooleanField(default=False, verbose_name='Is template?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_creator', to=settings.AUTH_USER_MODEL, verbose_name='Game creator'),
        ),
        migrations.AlterField(
            model_name='game',
            name='joiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_joiner', to=settings.AUTH_USER_MODEL, verbose_name='Game joiner'),
        ),
    ]
