# Generated by Django 2.1.3 on 2019-01-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0004_auto_20190102_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='GameData',
        ),
    ]
