# Generated by Django 2.1.7 on 2019-04-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0005_auto_20190417_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='creating_date',
        ),
    ]
