# Generated by Django 2.1.7 on 2019-04-30 16:23

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0006_auto_20190423_1423'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('active_games', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 16, 23, 3, 325800)),
        ),
    ]
