# Generated by Django 2.1.7 on 2019-04-30 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0008_auto_20190430_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 16, 59, 3, 246104, tzinfo=utc)),
        ),
    ]
