# Generated by Django 2.1.7 on 2019-04-30 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0009_auto_20190430_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 17, 0, 1, 111990, tzinfo=utc)),
        ),
    ]
