# Generated by Django 2.1.7 on 2019-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0010_auto_20190430_1700'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
