# Generated by Django 2.1.7 on 2019-05-27 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0011_auto_20190430_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fleet_composition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Fleet composition up to size'),
        ),
    ]
