# Generated by Django 2.1.7 on 2019-06-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0012_game_fleet_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='fleet_composition',
        ),
    ]
