# Generated by Django 2.2 on 2019-08-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0013_remove_game_fleet_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sea_battle.Game')),
            ],
            bases=('sea_battle.game',),
        ),
    ]
