# Generated by Django 2.1.3 on 2019-01-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0003_auto_20181123_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlemap',
            old_name='size_of_btlfld',
            new_name='field_size',
        ),
    ]
