# Generated by Django 2.1.3 on 2018-11-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='score',
        ),
    ]
