# Generated by Django 2.1.3 on 2018-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_userdata_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='opponent_user_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
