# Generated by Django 2.1.3 on 2018-11-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20181119_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
